site_name: MKDocs 튜토리얼
pages: 
  - 홈: index.md
  - 사용법: how.md
  - 세부사용법:
    - '테마': 'guide/theme.md'
    - '구조': 'guide/tree.md'
    - '기타': 'guide/others.md'
    - 'Admonition': 'guide/admonition.md'
    - '배포': 'guide/publish.md'
theme: readthedocs
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true